app:
  name: "go-clean-architecture"

postgres:
  tables:
    users: "users"

tokens:
  access_token_ttl: 2h
  refresh_token_ttl: 720h

http_server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 30s
  shutdown_timeout: 10s